### PR TITLE
Adding support to add labels in Batch operations

### PR DESCRIPTION
**Pull request by hamin**
I realize that you're probably not using this library anymore. Neoism seems to be the standard go neo4j client at the moment. However I really need to support Batch operations this lib was the most recent lib that worked for me. I added some support for dealing with labels and also did some go lint fixes. Thanks again for your work. The tests were super helpful :)

### CODE REVIEW

**Comment by cihangir** [comment]
hi @hamin 
Thanks for the awesome PR, can you please fix the tests?

**Comment by hamin** [comment]
@cihangir the tests are all passing on my machine..hmm

**Comment by hamin** [comment]
@cihangir i'm not that familiar with travis, do u know what version of neo4j is being tested against in travis?

**Comment by cihangir** [comment]
hi @hamin i updated travis file to test against multiple versions of neo4j, it was testing with 1.9 only
you can see the changes here https://github.com/cihangir/neo4j/pull/16 and i restarted your pr's build, lets see why it fails.

**Comment by cihangir** [comment]
ok you need to rebase against master and update your pr

**Comment by hamin** [comment]
@cihangir i rebased and master, PR should be updated now. Btw I know why it was probably failing. There's an issue with batch writes failing on Neo4J when you have http debug logging enabled like so:

`
org.neo4j.server.http.log.enabled=true
`

There's a github issue here https://github.com/neo4j/neo4j/issues/2517. Its not actually cl used yet, take a look at the comment, the issue still occurs. I confirmed this on my local neo4j server and that of my colleague @maggit who originally reported this issue for us a while ago and found the solution

**Comment by cihangir** [comment]
@hamin tests are failing for `neo4j versions < 2` and it is normal that they dont have `labels` support on 1.9 http://neo4j.com/news/neo4j-2-0-graphs-everyone/ , can you please add 
```
matrix:
  allow_failures:
    - env: NEO4J_VERSION="1.9.8"
```

to travis file? and lets see..

**Comment by hamin** [comment]
@cihangir i pushed the change to the travis file but seems like there's a merge conflict? Not sure

**Comment by cihangir** [comment]
You have my changes in your PR, that is causing(travis.ml) the problem. I am not sure how they sneaked into your pr, should be a rebase? problem.

**Comment by cihangir** [comment]
@hamin i removed neo4j 1.9 support from master branch, can you pull again pls?

**Comment by hamin** [comment]
@cihangir ok Travis tests seem to be passing :)

**Comment by cihangir** [comment]
Thanks!

**Comment by hamin** [comment]
:smiley_cat:

**Pull request merged**
